import utility
from utility_test import *


def q1():
    print utility.count_pattern('CGCGATACGTTACATACATGATAGACCGCGCGCGATCATATCGCGATTATC', 'CGCG')

def q2():
    print utility.count_pattern('GACCATCAAAACTGATAAACTACTTAAAAATCAGT', 'AAA')


def q3():
    utility.get_most_freq_n_mer('CGGAGGACTCTAGGTAACGCTTATCAGGTCCATAGGACATTCA', 3)

def q4():
    print utility.get_reverse_complement('GATTACA')


def q5():
    s = 'CGGAGGACTCTAGGTAACGCTTATCAGGTCCATAGGACATTCA'
    c = 3
    print utility.get_most_freq_n_mer(s, c)


def q6():
    s = 'GTCATTAGGACATTAAGCACCGAGGGTCATTAGCACCGAGGTCGTTTTGGACATTAATCGTTTTTCGTTTTGGACATTAAGTCATTAGTCATTATCGTTTTGTCATTAGCACCGAGGTCGTTTTGGACATTAAGGACATTAAGTCATTAGCGACAATGGCGACAATGGTCATTAGCGACAATGGGACATTAATCGTTTTGTCATTAGTCATTATCGTTTTGTCATTAGGACATTAAGGACATTAAGGACATTAATCGTTTTTCGTTTTGCGACAATGTCGTTTTGCGACAATGGCGACAATGTCGTTTTTCGTTTTGCGACAATGGCGACAATGGCACCGAGGGCGACAATGTCGTTTTGGACATTAAGGACATTAAGTCATTAGTCATTAGTCATTAGCGACAATGGTCATTAGCACCGAGGGCACCGAGGGCACCGAGGGGACATTAAGGACATTAAGTCATTAGCGACAATGTCGTTTTGGACATTAATCGTTTTGGACATTAAGTCATTAGCACCGAGGGGACATTAAGCGACAATGGTCATTAGCACCGAGGGCACCGAGGTCGTTTTGGACATTAAGTCATTAGCACCGAGGGCACCGAGGGTCATTAGTCATTAGGACATTAAGCGACAATGGGACATTAAGCACCGAGGGGACATTAAGCACCGAGGGGACATTAAGCGACAATGGGACATTAAGTCATTAGCACCGAGGGTCATTAGCACCGAGGGGACATTAAGCGACAATGGGACATTAAGCGACAATGTCGTTTTGTCATTAGCGACAATGGCACCGAGGGGACATTAAGGACATTAAGGACATTAAGTCATTAGGACATTAAGCACCGAGGGCACCGAGGTCGTTTTTCGTTTT'
    c = 13
    print utility.get_most_freq_n_mer(s, c)



q4()